# Generated by Django 6.0.6 on 2026-06-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
